# Generated by Django 2.2.3 on 2019-11-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anojs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
