# Generated by Django 2.2.3 on 2019-11-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anojs_app', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=100)),
                ('create_email', models.CharField(max_length=100)),
                ('animation_name', models.CharField(max_length=100)),
                ('animation_file', models.FileField(upload_to='')),
            ],
        ),
    ]
