# Generated by Django 2.2.3 on 2019-11-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anojs_app', '0004_animation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animation',
            old_name='create_email',
            new_name='creator_email',
        ),
    ]
